language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn run build
script:
  - yarn test  
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local-dir: dist
    on:
      branch: master
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: "React_SSR"
    region: "us-east-2"
    role: "arn:aws:iam::593103992301:role/service-role/React_SSR-role-ufockx2n"
    runtime: "nodejs12.x"
    handler_name: "handler"  
    zip: "server/index.js"
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST