language: node_js
node_js:
  - '12'
cache:
  yarn: true
  directories:
    - node_modules
before_deploy:
  - yarn global add travis-ci-cloudfront-invalidation
  - yarn run build
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_BUCKET
    skip_cleanup: true
    local-dir: dist
    on:
      branch: master
  - provider: lambda
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    function_name: "lambda-test"
    region: "us-east-1"
    role: "arn:aws:iam::0123456789012:role/lambda_basic_execution"
    runtime: "nodejs12.16.1"
    handler_name: "handler"  
    zip: "server/index.js"
after_deploy:
  - travis-ci-cloudfront-invalidation -a $AWS_ACCESS_KEY_ID -s $AWS_SECRET_ACCESS_KEY -c $CLOUDFRONT_ID -i '/*' -b $TRAVIS_BRANCH -p $TRAVIS_PULL_REQUEST